<Modules>
    <Module path="../lib/libnimMockNodes.dylib" />
    <Module path="../lib/libnimCodecs.dylib" />
    <Module path="../lib/libnimRecorder.dylib" />
    <Module path="../lib/libXnDevicesSensorV2.dylib" configDir="config"/>
    <Module path="../lib/libXnDeviceFile.dylib" configDir="config"/>
    <Module path="../lib/libXnVFeatures.dylib" configDir="config/XnVFeatures"/>
    <Module path="../lib/libXnVHandGenerator.dylib" configDir="config/XnVHandGenerator"/>
</Modules>
